### ISSUE TITLE
works fine in case person is standing little longer distance but not when person is at shorter distance

### ISSUE THREAD

**Issue by bandhavya** [jasonmayes/Real-Time-Person-Removal#10]
Sometimes it do not detect the person properly.. suddenly when we raise hand in the video. Video is very much distorted. How to make this functionality work more accurate ?

**Comment by jasonmayes** [comment]
You can try using a different model. Bodypix is not always optimal but was the only suitable one at time of making this. Since then many other models in TensorFlow.js for human body detection.
