### ISSUE TITLE
can this process of updating pixels be made faster for live streaming this video ?

### ISSUE THREAD

**Issue by bandhavya** [jasonmayes/Real-Time-Person-Removal#11]
I have a live video which will be streamed to the end user immediately. In this scenario, processed video (removing person) will be updated very slow and it will not be in sync with audio.

**Comment by jasonmayes** [comment]
Try something other than bodypix. Look for faster segmentation examples that you can port to tensorflow.js using our command line converter.  https://www.tensorflow.org/js/guide/conversion
