### ISSUE TITLE
Could you please explain what models are used here 

### ISSUE THREAD

**Issue by golkir** [jasonmayes/Real-Time-Person-Removal#2]
This is a great experiment. Could you please elaborate a little bit on how you make this work? Thanks

**Comment by MisakaMikoto128** [comment]
I also want to know

**Comment by jasonmayes** [comment]
As stated in the code comments it is the TensorFlow.js official bodypix model. (see https://github.com/tensorflow/tfjs-models/tree/master/body-pix)

You can see it in action here with my easy to get started tutorial on Glitch: https://glitch.com/~tensorflow-js-body-segmentation or Codepen: https://codepen.io/jasonmayes/pen/QWbNeJd

**Comment by b1xian** [comment]
detection->crop->paste?

**Comment by jasonmayes** [comment]
detection -> sliding window to improve detection -> background update -> body removal

**Comment by bebory** [comment]
how do you perform "body removal"?
