### ISSUE TITLE
How about using the mask provided in official BodyPix model?

### ISSUE THREAD

**Issue by futrime** [jasonmayes/Real-Time-Person-Removal#4]
BodyPix officially contains a mask function, which could straightly returns a mask of the image. How about using it instead?

**Comment by jasonmayes** [comment]
I am already using Bodypix but the mask alone is not enough to make it robust.

**Comment by james4388** [comment]
Sorry for late comment but you can you alpha channel of the mask and canvas globalCompositeOperation to blend it without for loop
