### ISSUE TITLE
I use your bodyPix to create realtime background removal

### ISSUE THREAD

**Issue by james4388** [jasonmayes/Real-Time-Person-Removal#5]
Mimic Zoom virtual background feature. Thanks for awesome tfjs
https://github.com/james4388/webcam-background-removal

**Comment by jasonmayes** [comment]
Nice! Would be great if you had a browser demo too ;-) Probably would get more people sharing it then too. Just a suggestion. Keep up the great work and thanks for letting me know! If you are on social media feel free to post a video / GIF using #madeWithTFJS so our team can find it!
